<html><head><title>HotRiches</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><style type="text/css"><!--body,td,th {color: #000000;font-family: Arial, Helvetica, sans-serif;font-size: 10pt;}body {background-color: #60778C;}.style1 {font-size: 15pt}--></style></head><body><table width="750" border="0" align="center" cellpadding="10" cellspacing="0" bgcolor="#FFFFFF" style="border: 1px solid black;"><tr align="center" valign="middle" bgcolor="#9DACBF"><td height="80">
<script language="JavaScript" src="http://www.paid-to-promote.com/banner.php?zoneid=87502&uid=8769&type=ban" type="text/javascript"></script>&nbsp;</td>
    <td width="160" rowspan="2">
<script language="JavaScript" src="http://www.paid-to-promote.com/sky.php?zoneid=87503&uid=8769&type=sky" type="text/javascript"></script>&nbsp;</td>
</tr><tr><td><p class="style1">Do you want to get PAID to read e-mail messages? Come on people! It's free money! Join HotRiches today! </p><table width="100%"  border="0" cellpadding="0" cellspacing="0">
      <tr><td><table width="300" border="0" align="right" cellpadding="5" cellspacing="0"><tr><td height="100">
<script language="JavaScript" src="http://www.paid-to-promote.com/cube.php?zoneid=87504&uid=8769&type=cube" type="text/javascript"></script>nbsp;</td></tr></table><p><strong>How HotRiches Works<br></strong>It's simple. We send you an e-mail with a link in it. You click the link to verify that you've read the e-mail, and we take you to the sponsor's web site. You then get a specified number of points (usually 3-5 points) per e-mail.</p><p><strong>Points? What about Cash?<br></strong>Whenever we receive payment from our advertisers, usually once per month, we convert all the points in the system into cash.</p><p>The current value of 1 point is $0.01. However, the more our members participate in sponsor offers, the more points can be worth. <strong><em>We currently share 60% of all revenue generated from our paid e-mails with our members</em>.</strong></p><p><strong>But there's more.<br></strong>Here on HotRiches, we also offer paid-to-click ads, where you get points just for clicking on certain ads in your members area. Other innovations are under way. </p></td><td width="160" align="left" valign="top" style="padding-left: 10px;"><table width="100%"  border="0" cellspacing="0" cellpadding="5" style="border: 1px solid gray;"><tr><td bgcolor="#92C989" style="border-bottom: 1px solid gray;"><strong>Member Benefits</strong></td></tr><tr><td><p>Highest paying rates in the industry! </p></td></tr><tr><td bgcolor="#F0F8EF">Cash out at only $5.00 </td></tr><tr><td>E-Mails sent out often! </td></tr><tr><td bgcolor="#F0F8EF">Generous referral program </td></tr><tr><td>60% revenue share </td></tr><tr><td bgcolor="#F0F8EF">Strict anti-cheating system </td></tr><tr><td>Much More! </td></tr></table><p><a href="/ptr/signup.asp" target="_top"><img src="/ptr/signup.jpg" width="135" height="42" border="0"></a></p></td></tr></table></td>
</tr>
</table>
</body></html>